ベストタイムを保存する機能を追加しました。
makutamoto/race-game pull request #3
Opened 2020-08-14 14:00 UTC by Raclamusi

## 追加内容
- レースでの最速タイムをバイナリで`bestTime/bestTime.dat`に保存するようにしました。
- タイトル画面でベストタイムを表示するようにしました。
- レースでより良いタイムが出たとき、「NEW RECORD!」と表示し、ベストタイムを更新するようにしました。
- 2P PLAY のときは、1P のタイムのみをベストタイムに反映するようにしました。
## 課題
- ファイルを削除することでしか、ベストタイムをリセットできません。
## スクリーンショット
タイトル画面
![bestTime_title](https://user-images.githubusercontent.com/61970673/90256954-7303d580-de81-11ea-8f92-1cb6ab8201b1.png)

2020-08-28 13:06 UTC, makutamoto commented
*.linkファイルが変更されていますが意図的ですか？

2020-08-28 13:23 UTC, makutamoto requested changes

2020-08-28 13:23 UTC, makutamoto commented on bestTime.c
> +		printf("saveBestTime: Failed to open a file: %s\n", path);
エラーメッセージはfprintf(stderr, "メッセージ");のようにしてStderrに出力してください。
標準出力に書き込むと描画がバグります。

2020-08-28 13:23 UTC, makutamoto commented on bestTime.c
> +		printf("loadBestTime: Failed to open a file: %s\n", path);
同上。

2020-08-28 13:23 UTC, makutamoto commented on title.c
> +	char buffer[18];
余裕をもって32byteぐらい取っといてほしいですね。

2020-08-29 02:39 UTC, Raclamusi commented
*.linkファイルを変更するつもりはまったくなかったので、変更は無かったことにしました。すみません。

2020-08-29 02:52 UTC, Raclamusi commented on bestTime.c
> +		printf("saveBestTime: Failed to open a file: %s\n", path);
エラーメッセージの出力先を標準エラー出力に変更しました。また、record.cにも同じ問題があったので、変更しました。

2020-08-29 03:05 UTC, Raclamusi commented on title.c
> +	char buffer[18];
32Byteに修正しました。
race.cでのバッファの取り方に合わせようと思いギリギリにしたのですが……。

2020-08-29 05:02 UTC, makutamoto commented on title.c
> +	char buffer[18];
よくみたらちゃんとバッファーオーバーラン対策されてましたね。
ごめんなさい…

2020-08-29 05:04 UTC, merged